### ISSUE TITLE
500 error on start screen

### ISSUE THREAD

**Issue by spaceo** [iamhabbeboy/laravel-vue-demo#2]
After I have been runing:
```
npm install
npm run dev
```
and
```
composer install (had to run composer update because it was complaining that composer.json and the lock file was out of sync)
 php artisan serve
```

I get a 500 server error when accessing: `http://localhost:8000`
Same goes for: `http://localhost:8000/home`

**Comment by spaceo** [comment]
If I go to the url that is written by Vite in the CLI:
<img width="303" alt="image" src="https://github.com/iamhabbeboy/laravel-vue-demo/assets/998889/c6cf8a1f-3d38-4d62-95d3-271031ec823e">

`http://localhost:5173`

I get this:
<img width="639" alt="image" src="https://github.com/iamhabbeboy/laravel-vue-demo/assets/998889/aab1ca84-8e70-48c7-b618-7f5ba83e6ef3">

(same goes for: `http://localhost:5173/home`)

**Comment by spaceo** [comment]
Ok. I forgot the whole Laravel setup thing with copying .env.example and generating key.
You could consider putting that in the README.md. Just to help other miserable souls :)

**Comment by iamhabbeboy** [comment]
@spaceo, I apologize for that, I will update the README.md anytime soon.
